Setup semaphore
Roandersonxd1/app-jetpack pull request #10
Opened 2020-11-16 20:15 UTC by Roandersonxd1

2020-11-17 18:00 UTC, edimossilva commented on .semaphore/semaphore.yml
> +  - name: Build
is this usefull? remove it?

2020-11-17 18:01 UTC, edimossilva requested changes

2020-11-17 18:01 UTC, edimossilva commented on .semaphore/semaphore.yml
> +#      when: pull_request !~ '.*'
remove comments

2020-11-17 18:01 UTC, edimossilva commented on .semaphore/semaphore.yml
> +#        - name: Integration Tests
remove coments

2020-11-18 12:05 UTC, Roandersonxd1 commented on .semaphore/semaphore.yml
> +  - name: Build
It is useful, because I need to say the semaphoreci that I'm using the android container

2020-11-18 12:05 UTC, Roandersonxd1 commented on .semaphore/semaphore.yml
> +#      when: pull_request !~ '.*'
Deleted

2020-11-18 12:05 UTC, Roandersonxd1 commented on .semaphore/semaphore.yml
> +#        - name: Integration Tests
Deleted

2020-11-18 12:05 UTC, merged